version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Src/Results"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: scope
    ignore:
      - dependency-name: "Microsoft.NET.Test.Sdk"
        versions:
          - "17.x"
    labels:
      - "dependencies"
      - "nuget"

  - package-ecosystem: "nuget"
    directory: "/Src/AspNetCore"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: scope
    ignore:
      - dependency-name: "Microsoft.NET.Test.Sdk"
        versions:
          - "17.x"
    labels:
      - "dependencies"
      - "nuget"
    allow:
      - dependency-type: "direct"
